### PR TITLE
style: treat warnings as errors

### PR DESCRIPTION
**Pull request by vil02**
Continuation of #18.

### CODE REVIEW

**Comment by Ramy-Badr-Ahmed** [comment]
> Continuation of #18.

Thanks @vil02 , 

Now my local version has become in sync 🙂

I set it up like like this: 
`add_compile_options(-Wall -Wextra -Wpedantic -Wunused-variable -Werror)`

Interested about other complile options?

**Comment by vil02** [comment]
> I set it up like like this: `add_compile_options(-Wall -Wextra -Wpedantic -Wunused-variable -Werror)`

`-Wunused-variable` seams to be part of [`-Wall`](https://gcc.gnu.org/onlinedocs/gfortran/Error-and-Warning-Options.html#index-Wall).

> Interested about other complile options?

Sure, but I would be careful here: some of the warnings are already included into the used flags, some of the warnings are _Fortran version specific_ etc.

**Comment by Ramy-Badr-Ahmed** [comment]
> `-Wunused-variable` seams to be part of [`-Wall`](https://gcc.gnu.org/onlinedocs/gfortran/Error-and-Warning-Options.html#index-Wall).
> 

Right, I'll change my local gfortran version.

> Sure, but I would be careful here: some of the warnings are already included into the used flags, some of the warnings are _Fortran version specific_ etc.

I previously used these:

```
-Wconversion-extra     # Warn about implicit conversions that may cause issues
-fno-backtrace         # Enable backtrace information for runtime errors
-fcheck=all            # Enable all runtime checks (bounds, uninitialized, etc.)
-finit-real=nan        # Initialize all REAL variables to NaN.
-finit-integer=0       # Initializes all integer variables to 0.
-ffpe-trap=all         # Trap floating-point exceptions (zero,overflow,underflow)
```

**Comment by vil02** [comment]
@Ramy-Badr-Ahmed: I added `-Wconversion-extra` in fb742a54683203cc01ab031c096a3182781e5eae.

Regarding other flags, which you listed: they are not _warnings_ and the discussion about them is out of scope of this PR. Few remarks for the future:
- I would not rely on `-finit-real` and `-finit-integer` but rather initialize all of the variable in the code,
- might make sense to use `-fcheck=all` and `-ffpe-trap=all` in the CI,
- `-fno-backtrace` is good for _local_ debugging, in my opinion,
- we might want to introduce two types of builds: _release_ and _debug_.

**Comment by Ramy-Badr-Ahmed** [comment]
Thanks for the feedback! I agree with your points, especially regarding introducing release and debug builds.

> @Ramy-Badr-Ahmed: I added `-Wconversion-extra` in [fb742a5](https://github.com/TheAlgorithms/Fortran/commit/fb742a54683203cc01ab031c096a3182781e5eae).
> 
> Regarding other flags, which you listed: they are not _warnings_ and the discussion about them is out of scope of this PR. Few remarks for the future:

Ok 👍 

> I would not rely on `-finit-real` and `-finit-integer` but rather initialize all of the variable in the code,

Yes, that's good practice. However, in the context of CI, these flags can help identify potential errors for contributors.

For example:

```fortran
real :: x
x = x + 1.0  ! x is uninitialized
``` 

If compiled with `-finit-real=nan`, the program will crash or return `NaN` when it encounters `x = NaN + 1.0`.

> might make sense to use `-fcheck=all` and `-ffpe-trap=all` in the CI,
> 
> `-fno-backtrace` is good for _local_ debugging, in my opinion,
> 
> we might want to introduce two types of builds: _release_ and _debug_.


For the builds, we could structure it like this:

* Debug build:
   * Include flags like `-fcheck=all`, `-ffpe-trap=all`, and keep `-finit-real=nan`, `-finit-integer` for uninitialized variable detection.
   * Keep backtrace enabled for detailed error reporting.

* Release build:
   * Strip runtime checks and use optimizations like `-O2/-O3` for better performance.

**Comment by vil02** [comment]
I do not have enough knowledge about FORTRAN to judge relevance of the other warning flags.

@Ramy-Badr-Ahmed: all of this sounds like a good idea for the future work.
@SatinWukerORIG: please consider this PR as _ready for a review_. I will not push anymore changes here unless necessary.

**Review by SatinWukerORIG — APPROVED** [review]
This is a good way to eliminate potential conflicts and improve code quality for learners to understand. I am merging it 👍

**Pull request merged**
