### PR TITLE
Added tests for the implemented Merge Sort Algorithm

### PR DESCRIPTION
**Pull request by Ramy-Badr-Ahmed**
### Desciption:

This pull request complements the implementation of the Merge Sort algorithm (#7) by adding tests, similar to those implemented for the other sorting algorithms (#8, #9, #10, #11 ).

### Additional Test Cases:

`tests_merge_sort.f90`: A test program that includes a variety of test cases to validate the merge_sort implementation. 

_______________
**Reference**

**[The Algorithm Design Manual, Latest edition](https://link.springer.com/book/10.1007/978-3-030-54256-6)**

### CODE REVIEW

**Review by Ramy-Badr-Ahmed — COMMENTED** [review]
Hi @SatinWukerORIG,
Looking forward to your review 🙂

**Review by Ramy-Badr-Ahmed — COMMENTED** [review]
Hi @SatinWukerORIG,
Looking forward to your review 🙂

**Review by SatinWukerORIG — APPROVED** [review]
LTGM 👍 
I think that is adequate amount of tests for your sorting algorithms. I might need help on implementing tests and examples on algorithms under math and searchs directories. 🤣

**Comment by Ramy-Badr-Ahmed** [comment]
> LTGM 👍 I think that is adequate amount of tests for your sorting algorithms. I might need help on implementing tests and examples on algorithms under math and searchs directories. 🤣

Right, will think about them 👍

**Pull request merged**
