### PR TITLE
Implemented Ternary Search Algorithm

### PR DESCRIPTION
**Pull request by Ramy-Badr-Ahmed**
### Description:

This pull request introduces an implementation of the **Ternary Search algorithm**.

It considers both **array-based** approach for searching elements within a sorted array and **function-based** approach for finding extremum points.

### Definition:

- **Ternary Search** is a divide-and-conquer algorithm used to search for an element in a **sorted array** or to find the minimum/maximum of [**unimodal functions**](https://myweb.uiowa.edu/pbreheny/7110/wiki/unimodal.html).

- It divides the search range into three parts and recursively eliminates two-thirds of the search space.

- **Array-based Ternary Search** works similarly to binary search, but it splits the array into three parts instead of two, allowing for potentially fewer comparisons in large datasets.

- **Function-based Ternary Search** finds the minimum or maximum value of a unimodal function over a given interval, narrowing the search range by evaluating two intermediate points.
- **Time Complexity:**
    - **Array-based**: `O(log3(n))`, where `n` is the number of elements.
    - **Function-based**: Dependent on the precision (`tol`) specified.

### Implementation Details:

`ternary_search.f90`: Contains the `ternary_search_module` with:

> `ternary_search_array`: A recursive function that searches for a target element in a sorted array by dividing it into three parts.
`ternary_search_minimum`: A recursive function that finds the minimum of a unimodal function by evaluating it in smaller intervals.
`ternary_search_maximum`: A recursive function that finds the maximum of a unimodal function using a similar approach as the minimum search.

The module supports searching in arrays and unimodal functions with customisable precision for the function-based search.

**Notes**

- The **array-based ternary search** requires the input array to be sorted. If the array is unsorted, the search results will be incorrect. A sorting algorithm (e.g., #8  or #7) must be applied to the array before using ternary search.

- The **function-based ternary search** assumes that the input function is [unimodal](https://myweb.uiowa.edu/pbreheny/7110/wiki/unimodal.html) (i.e., it has only one minimum or maximum in the interval). If the function is not unimodal, the algorithm is not relevant.

### Example Usage:

`example_ternary_search_array.f90`: Demonstrates the usage of ternary_search_array:

- Searches for a target value in a sorted array:

```fortran
Array: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
Target: 17

Output: Target found at index: 9
``` 

`ternary_search_function_based.f90`: Demonstrates the usage of `ternary_search_minimum` and `ternary_search_maximum`:

- Finding Minimum:

```fortran
Function: (x - 5.0)**2 + cos(x)
Range: [0.0, 10.0]

Output: Minimum at x ≈ 4.51 with value ≈ 0.0391.
``` 

- Finding Maximum:
```fortran
Function: -(x - 5.0)**2 + cos(x)
Range: [0.0, 10.0]

Output: Maximum at x ≈ 5.39 with value ≈ 0.4748
``` 

_______________
**Reference**

**[The Algorithm Design Manual, Latest edition](https://link.springer.com/book/10.1007/978-3-030-54256-6)**

### CODE REVIEW

**Review by Ramy-Badr-Ahmed — COMMENTED** [review]
Hi @SatinWukerORIG ,
Looking forward to your review 🙂

**Review by Ramy-Badr-Ahmed — COMMENTED** [review]
@SatinWukerORIG 

New #13 checks are passing: 

[ci](https://github.com/TheAlgorithms/Fortran/actions/runs/11019116220)

Considered fprettify #27 

All checks have passed 👍

**Review by SatinWukerORIG — COMMENTED** [review]
The code looks good! But why are you adding a "_based" at the end of the file name?

**Comment by Ramy-Badr-Ahmed** [comment]
> The code looks good! But why are you adding a "_based" at the end of the file name?

Thanks! 👍 

I just added it to easily differentiate between the two use cases of the algorithm. The algorithm can be used to sort arrays as well as searching for min/max points in unimodal functions.

Putting them in one program is possible, but will just make the demo too long. We can enumerate them instead "_1" and "_2".

**Review by SatinWukerORIG — APPROVED** [review]

**Pull request merged**
